Indices = randperm(300); % Here we randomly permute data indices
for sample = 1:150
 TestingDataClass0(:,sample) = ...
[A.Data(300+Indices(sample)).Normal.Moments.N30,...
A.Data(300+ Indices(sample)).Normal.HuInvariants.I1];
 TestingDataClass1(:,sample) = ...
[D.Data(300+Indices(sample)).Normal.Moments.N30,...
D.Data(300+Indices(sample)).Normal.HuInvariants.I1];
end
for sample = 1:150
 FinalTestClass0(:,sample) = ...
 [A.Data(300+Indices(sample)).Normal.Moments.N30,...
A.Data(300+Indices(sample)).Normal.HuInvariants.I1];
 FinalTestClass1(:,sample) = ...
[D.Data(300+Indices(sample)).Normal.Moments.N30,...
D.Data(300+Indices(sample)).Normal.HuInvariants.I1];
end
Indices = randperm(300); % Here we randomly permute data indices
for sample = 1:150
 TestingDataClass0(:,sample) = ...
[A.Data(300+Indices(sample)).Normal.Moments.N30,...
A.Data(300+ Indices(sample)).Normal.HuInvariants.I1];
 TestingDataClass1(:,sample) = ...
[D.Data(300+Indices(sample)).Normal.Moments.N30,...
D.Data(300+Indices(sample)).Normal.HuInvariants.I1];
end
for sample = 1:150
 FinalTestClass0(:,sample) = ...
 [A.Data(300+Indices(sample)).Normal.Moments.N30,...
A.Data(300+Indices(sample)).Normal.HuInvariants.I1];
 FinalTestClass1(:,sample) = ...
[D.Data(300+Indices(sample)).Normal.Moments.N30,...
D.Data(300+Indices(sample)).Normal.HuInvariants.I1];
end
figure; boxplot(ErrorSum); ylabel('ErrorSum'); xlabel('NetNumber');